branch: master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  # - ['@semantic-release/exec', { prepareCmd: "echo ${nextRelease.version} > VERSION.txt" }]
  - '@semantic-release/github'
  - ['@semantic-release/git', { assets: ['CHANGELOG.md', 'VERSION.txt', 'package.json'] }]
