branch: master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - ['@semantic-release/git', { assets: ['CHANGELOG.md', 'package.json', 'package-lock.json'] }]
