name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
    - name: Conventional Changelog Action
      uses: willclark/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.ACTION_TOKEN }}
        version-file: 'package-lock.json,package.json'
