name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3.4.0
      with:
        github-token: ${{ secrets.ACTION_TOKEN }}
        version-file: package-lock.json
