name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        release-count: '0'
        git-user-name: willclark
        github-token: ${{ secrets.ACTION_TOKEN }}
        version-file: 'package.json'
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
